package advanced_java2_deitel.chapter17_corba;


/**
 * com/deitel/advjhtp1/idl/clock/SystemClockHolder.java
 * Generated by the IDL-to-Java compiler (portable), version "3.0"
 * from systemclock.idl
 * Sunday, July 1, 2001 10:36:53 PM PDT
 */


// The definition of the CORBA-enabled service
public final class SystemClockHolder implements org.omg.CORBA.portable.Streamable {
    public SystemClock value = null;

    public SystemClockHolder() {
    }

    public SystemClockHolder(SystemClock initialValue) {
        value = initialValue;
    }

    public void _read(org.omg.CORBA.portable.InputStream i) {
        value = SystemClockHelper.read(i);
    }

    public void _write(org.omg.CORBA.portable.OutputStream o) {
        SystemClockHelper.write(o, value);
    }

    public org.omg.CORBA.TypeCode _type() {
        return SystemClockHelper.type();
    }

}